#pragma once
#include <json/json.h>

#include <memory>

#include "common/json_util.h"
#include "common/math_util.h"

namespace worldview {
namespace sim {

enum FunctionId {
  FUNCTION_NONE = 0,
  FUNCTION_NOA = 1,
  FUNCTION_APA = 2,
  FUNCTION_ACC = 3,
  FUNCTION_LKA = 4,
  FUNCTION_SUMMON = 5,
  FUNCTION_LKA_PLUS = 6,
  FUNCTION_CITY_NOA = 7,
  FUNCTION_MAPLESS_NOA = 8
};

enum BehaviorChoice {
  BEHAVIOR_CHOICE_INVALID = 0,
  BEHAVIOR_CHOICE_CRUISE = 1,
  BEHAVIOR_CHOICE_LANE_CHANGE = 2,
  BEHAVIOR_CHOICE_MERGE = 3,
  BEHAVIOR_CHOICE_SPLIT = 4,
  BEHAVIOR_CHOICE_MRM = 5,
  BEHAVIOR_CHOICE_MRC = 6,
  BEHAVIOR_CHOICE_SLOT_PARK = 7
};

enum BehaviorAction {
  BEHAVIOR_ACTION_INVALID = 0,
  BEHAVIOR_ACTION_PRE_LEFT_CHANGE = 1,
  BEHAVIOR_ACTION_PRE_RIGHT_CHANGE = 2,
  BEHAVIOR_ACTION_LEFT_CHANGE = 3,
  BEHAVIOR_ACTION_RIGHT_CHANGE = 4,
  BEHAVIOR_ACTION_ABORT_CHANGE = 5,
  BEHAVIOR_ACTION_MERGE_LEFT = 6,
  BEHAVIOR_ACTION_MERGE_RIGHT = 7,
  BEHAVIOR_ACTION_KEEP_PATH = 8,
  BEHAVIOR_ACTION_SEARCH_SLOTS = 9,
  BEHAVIOR_ACTION_ACTIVE_PARKING = 10,
  BEHAVIOR_ACTION_PAUSE_PARKING = 11,
  BEHAVIOR_ACTION_COMPLETE_PARKING = 12,
  BEHAVIOR_ACTION_SUMMON_FRONT = 13,
  BEHAVIOR_ACTION_SUMMON_REAR = 14,
  BEHAVIOR_ACTION_SUMMON_STOP = 15
};

enum BehaviorLCEnableStatus {
  BEHAVIOR_LC_ENABLE_NONE = 0,
  BEHAVIOR_LC_ENABLE_LEFT = 1,
  BEHAVIOR_LC_ENABLE_RIGHT = 2,
  BEHAVIOR_LC_ENABLE_BOTH = 3
};

}  // namespace sim
}  // namespace worldview